In [1]:
import torch as t
import numpy as np

两个`tensor` 之间，相同位置的元素可以进行相关的运算

In [2]:
t1 = t.tensor([
    [1, 1],
    [2, 2]
])

t2 = t.tensor([
    [2, 2],
    [1, 1]
])

t1 + t2

tensor([[3, 3],
        [3, 3]])

那么可以定义两个 `shape` 相同的张量可以进行元素间运算。但是张量和数字又能运算


In [6]:
t1 + 2

tensor([[3, 3],
        [4, 4]])

很早之前我是认为， 数字能作用到每个元素上。

但是这样其实有误导性质,如下方式，不同 `shape` 照样可以计算。

In [15]:
t1 + t.tensor([1, 1])

tensor([[2, 2],
        [3, 3]])

其实以上两种情况都是利用了广播机制，让数字变成了与 `t1` 相同形状的张量

In [4]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [21]:
# 其实是这样的
t1 + t.tensor(np.broadcast_to(2, t1.shape), dtype = t.int)

tensor([[3, 3],
        [4, 4]])

更加了解一些广播机制


In [31]:
t3 = t.tensor([
    [1,1],
    [1,1]
], dtype=t.float32)
t4 = t.tensor([2, 4], dtype = t.float32)
print(t3)
print(t3.shape)
print(t4)
print(t4.shape)

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
tensor([2., 4.])
torch.Size([2])


In [33]:
print(np.broadcast_to(t4.numpy(), t3.shape))
t3 + t4

[[2. 4.]
 [2. 4.]]


tensor([[3., 5.],
        [3., 5.]])

当然了，算数运算都算元素间运算，关系运算符也一样。

其中也是用到了广播机制

In [34]:
t5 = t.tensor([
    [0, 5, 0],
    [6, 0, 7],
    [0, 8, 0],
])

In [37]:
print(t5 == 0)
print(t5 >= 0)
print(t5 > 0)
print(t5 <= 0)
print(t5 <= 7)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])
tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])


In [38]:
t5 <= t.tensor(np.broadcast_to(7, t5.shape))

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

还可以对每个元素做函数操作，这里就理解成函数作用到每个元素上就好。

In [44]:
t5.neg()

t.neg(t5)

t5 * -1

tensor([[ 0, -5,  0],
        [-6,  0, -7],
        [ 0, -8,  0]])