In [1]:
import torch as t
import numpy as np

把如下三个当做 4 * 4 图片

In [2]:
t1 = t.tensor([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
])
t2 = t.tensor([
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
])
t3 = t.tensor([
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
])

然后这三张图是要在一个批次中，放在一个张量中。

In [8]:
tt = t.stack((t1, t2, t3)) # 连接三个 tesnor 在一个新的轴上
# 3 * 4 * 4 batch * height * width
print(tt)
print(tt.shape)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])
torch.Size([3, 4, 4])


但是我们知道 `CNN` 中张量的 `shape` 是 `[B, C, H, W]` 少了一个 `color channel`

In [9]:
tt = tt.reshape(3, 1, 4, 4) # 不影响总数，可以这么做
tt

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

第一轴代表一个批次中的图片，长度为 `3` 说明三张图。

而第二轴代表每张图的颜色通道，长度为 `1` ，说明这张图只有一个通道，一般会有多个通道，得到的图片也不同。 

第三四轴，图片高和宽。

分析这个维度个人觉得有一点困难，主要是通过输出 `shape` 去理解的。用不同的维度代表不同的特征，而特征有许多的不同数量，这就是轴长。

In [10]:
tt[0] # 批次中的第一张图片

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [11]:
tt[0][0] #第一张图第一个颜色通道

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [13]:
tt[0][0][0] # 第一张图第一个颜色通道第一个高(也就是第一行像素，方便理解的说法)，

tensor([1, 1, 1, 1])

In [14]:
tt[0][0][0][0]  # 第一张图第一个颜色通道第一个高的第一个像素点

tensor(1)

对于这一个张量，肯定不是要把它们全部压平变成一个轴，而是选择性地压平。

这样就失去了很多信息，通道数和批次都没了。而我们只是想让图片高和宽消失，成为一行。

In [15]:
tt.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

如何用 `reshape` 方法来实现部分压平，保留批次的信息，通道、高、宽都不需要。

In [23]:
#tt.reshape(3, 1, 4, 4)
tt.reshape(3, -1) # -1 的作用，通过前头已有的轴长，来自动重塑
tt.reshape(tt.shape[0], -1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

如果用 `flatten` 其实也是一样的，这样也理解了 `start_dim` 参数，其实就是和如上做法一致。

In [22]:
tt.flatten(start_dim = 1) # 从第二轴开始压平，包括第二轴，第一轴得以保留

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

做一个有三通道的 `2 * 2` 的图片

`[C, H, W]`

In [26]:
r = t.ones(1, 2, 2)
g = t.ones(1, 2, 2) + 1
b = t.ones(1, 2, 2) + 2
print(r)
print(g)
print(b)

tensor([[[1., 1.],
         [1., 1.]]])
tensor([[[2., 2.],
         [2., 2.]]])
tensor([[[3., 3.],
         [3., 3.]]])


In [28]:
img = t.cat((r, g, b), dim = 0)
img

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [29]:
img.shape

torch.Size([3, 2, 2])

In [35]:
print(img.flatten(start_dim = 0))
print(img.flatten(start_dim = 1))
print(img.flatten(start_dim = 2)) # reshape(3, 2, -1) -> reshape(3, 2, 2)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])


In [44]:
imgt = t.cat((r, g, b), dim = 1)
print(imgt)
print(imgt.shape)

tensor([[[1., 1.],
         [1., 1.],
         [2., 2.],
         [2., 2.],
         [3., 3.],
         [3., 3.]]])
torch.Size([1, 6, 2])


In [43]:
imgt = t.cat((r, g, b), dim = 2)
print(imgt)
print(imgt.shape)

tensor([[[1., 1., 2., 2., 3., 3.],
         [1., 1., 2., 2., 3., 3.]]])
torch.Size([1, 2, 6])
