In [1]:
import torch as t
import numpy as np

张量的 减少 操作，我理解是，因为通过此操作，生成的张量的秩会减少，甚至元素数都减少。

In [7]:
tt = t.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0],
], dtype =  t.float32)

tt.sum()

tensor(8.)

直接变成了 0 阶张量，所以 `sum` 可以称作减少操作。操作的范围是张量的所有元素。

In [8]:
print(tt.prod())
print(tt.mean())
print(tt.std())

tensor(0.)
tensor(0.8889)
tensor(1.1667)


当然，这些操作可以直接猜到，也可以作用在特定的轴上。(参考 `flatten`)

In [9]:
tt = t.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
], dtype = t.float32)

In [10]:
tt.sum(dim = 0)

tensor([6., 6., 6., 6.])

In [11]:
tt.sum(dim = 1)

tensor([ 4.,  8., 12.])

看到这两个结果，可以直观地发现，`dim = 0` 是以一列一列的方式相加得到结果。


In [14]:
tt[0] + tt[1] + tt[2]

tensor([6., 6., 6., 6.])

`dim = 1` 是每一行所有数字相加得到结果

In [16]:
print(tt[0].sum())
print(tt[1].sum())
print(tt[2].sum())

tensor(4.)
tensor(8.)
tensor(12.)


如果是二维的例子，说实话只需要利用行列理解就可以。但是毕竟张量可以有更高阶。

所以我自己有一点观察到 `shape = (3 * 4)` 形状的张量，在 `dim = 0` 的时候，变成了 `shape = (4)`，可以理解为第一个轴被减去了，保留了第二个轴。

为什么？因为如果求和操作是在第一个轴，那么第一个轴上的三个元素，求和操作后，第一个轴就没有轴长，就等于这个轴消失，但是第二个轴不受影响。

这就是 `dim = n` 沿着第 `n` 个轴执行操作的逻辑。还是不够理解的话，建议看一个知乎问答。

如果 `dim = 0`，那么操作对象是 `index = 0` 变化的元素，也就是 `tt[0][0], tt[1][0], tt[2][0]`，`tt[0][1], tt[1][1], tt[2][1]` 这样的范围。所以对他们求和的过程就好像对这个轴做了一个求和然后让这个轴消失的操作。

`argmax` 函数用于找到张量中最大值得位置。


In [19]:
tt = t.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=t.float32)

In [20]:
tt.argmax()

tensor(11)

为什么是 `11` ? 其实你把 `tt` 摊平了，就是第 `12` 个元素，也就是 `index` 为 `11` 的位置。

In [22]:
tt.max(dim = 0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

`max` 要是指定 `dim` 那么会在指定 `dim` 上找最大值，并且返回对应的位置

例如，`dim = 0` 就是一列一列看，第一列最大的是 `4`，位置也是第三个, `index` 便是 `2`

In [24]:
tt.argmax(dim = 0) # argmax 也证明了这一点

tensor([2, 1, 1, 2])

In [26]:
print(tt.max(dim = 1))
print(tt.argmax(dim = 1))

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))
tensor([3, 2, 3])


如果我们想获得张量中的值,转化为 `python` 中的数据结构

In [34]:
tt.max().item() # 用于 0 阶张量的取值, 

array(5., dtype=float32)

In [31]:
tt.argmax(dim = 0).tolist() # 1 阶 乃至多阶转为 list

[2, 1, 1, 2]

In [35]:
tt.argmax(dim = 0 ).numpy() # 0 阶至高阶转成 numpy.darray

array([2, 1, 1, 2], dtype=int64)