In [1]:
import torch as t
import numpy as np

In [2]:
tt = t.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
])

In [3]:
tt.shape

torch.Size([3, 4])

In [4]:
len(tt.shape)

2

In [5]:
tt.prod()

tensor(1296)

In [6]:
tt.numel() # reshape 需要考虑这个

12

In [7]:
tt.reshape(1, 12)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [8]:
tt.reshape(12, 1)

tensor([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]])

In [9]:
tt.reshape(1, 12).squeeze()

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [22]:
tt.reshape(12,1).unsqueeze(dim = 0).shape

torch.Size([1, 12, 1])

flatten 就是一阶张量包含所有数据。

In [11]:
def flatten(tt):
    return tt.reshape(1, -1).squeeze() #-1 代表根据数量来决定这一轴的长度
flatten(tt)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [13]:
t1 = t.tensor([
    [1, 2],
    [3, 4],
])

t2 = t.tensor([
    [5, 6],
    [7, 8],
])

In [15]:
t.cat((t1, t2), dim = 0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [16]:
t.cat((t1, t2), dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])